# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_gettemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetTemp',
        ),
    ]
